version: '3.8'

services:
  app:
    image: node:22.18.0
    container_name: lasmunecasderamon
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./lasmunecasderamon:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - lasmunecasnet
    depends_on:
      - db

networks:
  lasmunecasnet:
    external: true

volumes:
  db_data:
