services:
  app:
    image: node:22.18.0
    container_name: lasmunecasderamon
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - lasmunecasnet
networks:
  lasmunecasnet:
    external: true