import {
  SELECT_CONTENT_WIDE_CLASS,
  SELECT_INPUT_CLASS,
  SELECT_LABEL_CLASS,
  SELECT_MULTI_TRIGGER_CLASS,
  SELECT_SEARCH_INPUT_CLASS,
  SELECT_SEARCH_WRAPPER_CLASS,
  SELECT_TRIGGER_CLASS
} from '@/components/shared/selectStyles';

export const ORDER_FIELD_LABEL_CLASS = SELECT_LABEL_CLASS;

export const ORDER_FIELD_TRIGGER_CLASS = SELECT_TRIGGER_CLASS;

export const ORDER_MULTISELECT_TRIGGER_CLASS = SELECT_MULTI_TRIGGER_CLASS;

export const ORDER_FIELD_INPUT_CLASS = SELECT_INPUT_CLASS;

export const ORDER_FIELD_INPUT_WITH_ICON_CLASS = `${ORDER_FIELD_INPUT_CLASS} pl-8`;

export const ORDER_FIELD_POPOVER_CLASS = `${SELECT_CONTENT_WIDE_CLASS} z-[9999]`;

export const ORDER_FIELD_SEARCH_WRAPPER_CLASS = SELECT_SEARCH_WRAPPER_CLASS;

export const ORDER_FIELD_SEARCH_INPUT_CLASS = SELECT_SEARCH_INPUT_CLASS;

export const ORDER_SELECTED_TAG_CLASS =
  'rounded-full bg-black/5 text-gray-700 dark:bg-white/10 dark:text-zinc-100 px-2.5 py-1 text-xs font-medium';
