-- ============================================================
-- Consolidated Migration — lasmunecasderamon-dashboard (Postgres)
-- Generado: 2026-09-20
-- Origen: 11 archivos individuales consolidados en uno solo
--   - create_anticipo_historial.sql
--   - add_monto_to_solicitudes_anulacion_ventas.sql
--   - fix_detalle_pedido_id_type.sql
--   - add_es_temporal_to_servicios.sql
--   - add_performance_indexes.sql
--   - add_cargo_tarjeta_to_ventas_y_cajas.sql
--   - create_query_logs_table.sql
--   - add_composite_indexes.sql
--   - add_force_password_change.sql
--   - postgres_runtime_support.sql
--   - postgres_anticipo_history_backfill.sql
-- Idempotente: todos los DDL usan IF NOT EXISTS / DO $$ guard.
-- Runner: node scripts/run-migrations.mjs (lee solo este archivo)
-- Baseline schema completo en: database/lasmunecasderamon.postgres.sql
-- ============================================================

-- 1) anticipo_historial ------------------------------------------------
CREATE TABLE IF NOT EXISTS anticipo_historial (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  anticipo_id varchar(36) NOT NULL,
  accion varchar(50) NOT NULL,
  usuario_id varchar(36) DEFAULT NULL,
  fecha_crea timestamp NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_anticipo_historial_anticipo FOREIGN KEY (anticipo_id) REFERENCES anticipos (id_anticipo) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_anticipo_historial_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id_usuario) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS fk_anticipo_historial_anticipo_id ON anticipo_historial (anticipo_id);
CREATE INDEX IF NOT EXISTS fk_anticipo_historial_usuario_id ON anticipo_historial (usuario_id);

-- 2) solicitudes_anulacion_ventas.monto --------------------------------
ALTER TABLE solicitudes_anulacion_ventas
ADD COLUMN IF NOT EXISTS monto DECIMAL(12,2) NULL;

-- 3) detalle_pedidos_anfitrionas.detalle_pedido_id type fix ---------------
ALTER TABLE detalle_pedidos_anfitrionas
  ALTER COLUMN detalle_pedido_id TYPE varchar(36) USING detalle_pedido_id::varchar(36),
  ALTER COLUMN detalle_pedido_id SET NOT NULL;

-- 4) servicios.es_temporal + servicio_original_id -----------------------
ALTER TABLE servicios
  ADD COLUMN IF NOT EXISTS es_temporal smallint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS servicio_original_id varchar(36) DEFAULT NULL;

-- 5) performance indexes ------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_ventas_estado_fecha ON ventas (estado, fecha_crea);
CREATE INDEX IF NOT EXISTS idx_servicios_estado_fecha ON servicios (estado, fecha_crea);
CREATE INDEX IF NOT EXISTS idx_detalle_ventas_venta_id ON detalle_ventas (venta_id);
CREATE INDEX IF NOT EXISTS idx_detalle_ventas_producto_id ON detalle_ventas (producto_id);
CREATE INDEX IF NOT EXISTS idx_detalle_servicios_servicio_id ON detalle_servicios (servicio_id);
CREATE INDEX IF NOT EXISTS idx_detalle_servicios_usuario_id ON detalle_servicios (usuario_id);

-- 6) ventas/cajas.cargo_tarjeta ---------------------------------------
ALTER TABLE ventas
  ADD COLUMN IF NOT EXISTS cargo_tarjeta int NOT NULL DEFAULT 0;
ALTER TABLE cajas
  ADD COLUMN IF NOT EXISTS cargo_tarjeta int NOT NULL DEFAULT 0;

-- 7) query_logs --------------------------------------------------------
CREATE TABLE IF NOT EXISTS query_logs (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sql text NOT NULL,
  params_count int NOT NULL DEFAULT 0,
  duration_ms decimal(10,1) NOT NULL,
  query_type varchar(20) NOT NULL,
  query_count int DEFAULT NULL,
  avg_query_ms decimal(10,1) DEFAULT NULL,
  total_query_time_ms decimal(10,1) DEFAULT NULL,
  created_at timestamp NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_query_logs_created_at ON query_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_query_logs_duration_ms ON query_logs (duration_ms);
CREATE INDEX IF NOT EXISTS idx_query_logs_type ON query_logs (query_type);

-- 8) composite indexes -------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_ventas_usuarios_venta_id ON ventas_usuarios (venta_id);
CREATE INDEX IF NOT EXISTS idx_ventas_usuarios_usuario_id ON ventas_usuarios (usuario_id);
CREATE INDEX IF NOT EXISTS idx_retiros_caja_caja_id ON retiros_caja (caja_id);
CREATE INDEX IF NOT EXISTS idx_cajas_estado ON cajas (estado);
CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON pedidos (estado);
CREATE INDEX IF NOT EXISTS idx_pedidos_mesero_id ON pedidos (mesero_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_usuarios_usuario_id ON pedidos_usuarios (usuario_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_usuarios_pedido_id ON pedidos_usuarios (pedido_id);
CREATE INDEX IF NOT EXISTS idx_comisiones_venta_id ON comisiones (venta_id);
CREATE INDEX IF NOT EXISTS idx_comisiones_servicio_id ON comisiones (servicio_id);
CREATE INDEX IF NOT EXISTS idx_ventas_caja_estado_fecha ON ventas (caja_id, estado, fecha_crea);
CREATE INDEX IF NOT EXISTS idx_servicios_caja_estado_fecha ON servicios (caja_id, estado, fecha_crea);
CREATE INDEX IF NOT EXISTS idx_solicitudes_servicios_estado ON solicitudes_servicios (estado);
CREATE INDEX IF NOT EXISTS idx_asistencias_usuario_estado ON asistencias (usuario_id, estado);
CREATE INDEX IF NOT EXISTS idx_anticipos_usuario_estado ON anticipos (usuario_id, estado);
CREATE INDEX IF NOT EXISTS idx_detalle_propinas_usuario_id ON detalle_propinas (usuario_id);
CREATE INDEX IF NOT EXISTS idx_horas_extras_usuario_id ON horas_extras (usuario_id);
CREATE INDEX IF NOT EXISTS idx_detalle_comisiones_usuario_id ON detalle_comisiones (usuario_id);
CREATE INDEX IF NOT EXISTS idx_logins_usuario_id ON logins (usuario_id);
CREATE INDEX IF NOT EXISTS idx_propinas_venta_id ON propinas (venta_id);
CREATE INDEX IF NOT EXISTS idx_detalle_ventas_hostess_id ON detalle_ventas (hostess_id);

-- 9) usuarios.force_password_change -----------------------------------
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'usuarios' AND column_name = 'force_password_change') THEN
    ALTER TABLE usuarios ADD COLUMN force_password_change smallint NOT NULL DEFAULT 0;
    ALTER TABLE usuarios ALTER COLUMN force_password_change SET DEFAULT 1;
  END IF;
END $$;

-- 10) runtime support (push_tokens + deferrable FKs + identity seq) ----
ALTER TABLE backups ADD COLUMN IF NOT EXISTS json_data text;
CREATE TABLE IF NOT EXISTS push_tokens (
  id varchar(36) PRIMARY KEY,
  usuario_id varchar(36) NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  token text NOT NULL UNIQUE,
  device_type varchar(30) NOT NULL DEFAULT 'web'
);
DO $$ DECLARE fk record; BEGIN
  FOR fk IN SELECT conrelid::regclass AS table_name, conname
    FROM pg_constraint WHERE contype = 'f' AND connamespace = current_schema()::regnamespace
  LOOP
    EXECUTE format('ALTER TABLE %s ALTER CONSTRAINT %I DEFERRABLE INITIALLY IMMEDIATE', fk.table_name, fk.conname);
  END LOOP;
END $$;
DO $$ DECLARE col record; highest bigint; BEGIN
  FOR col IN SELECT table_name, column_name,
      pg_get_serial_sequence(format('%I.%I', table_schema, table_name), column_name) AS seq
    FROM information_schema.columns
    WHERE table_schema = current_schema() AND is_identity = 'YES'
  LOOP
    EXECUTE format('SELECT max(%I) FROM %I', col.column_name, col.table_name) INTO highest;
    PERFORM setval(col.seq, COALESCE(highest, 1), highest IS NOT NULL);
  END LOOP;
END $$;

-- 11) anticipo_historial backfill (idempotente) ------------------------
WITH events AS (
  SELECT id_anticipo AS anticipo_id, 'solicitud' AS accion, usuario_id, fecha_crea FROM anticipos
  UNION ALL SELECT id_anticipo, 'aprobado', NULL, fecha_aprobacion FROM anticipos WHERE fecha_aprobacion IS NOT NULL
  UNION ALL SELECT id_anticipo, 'rechazado', NULL, fecha_mod FROM anticipos WHERE estado = 3 AND fecha_mod IS NOT NULL
  UNION ALL SELECT a.id_anticipo, 'entregado', u.id_usuario, a.fecha_entrega FROM anticipos a
    LEFT JOIN usuarios u ON u.id_usuario = a.entregado_por WHERE a.fecha_entrega IS NOT NULL
)
INSERT INTO anticipo_historial (anticipo_id, accion, usuario_id, fecha_crea)
SELECT e.anticipo_id, e.accion, e.usuario_id, e.fecha_crea FROM events e
WHERE NOT EXISTS (SELECT 1 FROM anticipo_historial h
  WHERE h.anticipo_id = e.anticipo_id AND h.accion = e.accion AND h.fecha_crea = e.fecha_crea);
