"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
//
// NOTA: Los imports estáticos fueron reemplazados por loaders dinámicos.
//       Los archivos .bones.json ahora se cargan bajo demanda por ruta.
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

configureBoneyard({"color":"#f3f4f6","animate":"pulse"})

// ── Lazy loaders: cada archivo .bones.json se convierte en un chunk separado ──
// Los strings de import son estáticos para que el bundler pueda code-splitearlos.

const BONE_LOADERS: Record<string, () => Promise<{ default: any }>> = {
  'anfitriona-asistencias-main': () => import('./anfitriona-asistencias-main.bones.json'),
  'anfitriona-dashboard-main': () => import('./anfitriona-dashboard-main.bones.json'),
  'cajero-anticipos-main': () => import('./cajero-anticipos-main.bones.json'),
  'cajero-asistencias-main': () => import('./cajero-asistencias-main.bones.json'),
  'cajero-propinas-main': () => import('./cajero-propinas-main.bones.json'),
  'error-logs-main': () => import('./error-logs-main.bones.json'),
  'garzon-anticipos-main': () => import('./garzon-anticipos-main.bones.json'),
  'garzon-asistencias-main': () => import('./garzon-asistencias-main.bones.json'),
  'garzon-propinas-main': () => import('./garzon-propinas-main.bones.json'),
  'profile-main': () => import('./profile-main.bones.json'),
  'category-products-mobile': () => import('./category-products-mobile.bones.json'),
  'category-products-table': () => import('./category-products-table.bones.json'),
  'dashboard-main': () => import('./dashboard-main.bones.json'),
  'orders-main': () => import('./orders-main.bones.json'),
  'reports-main': () => import('./reports-main.bones.json'),
}

// ── Mapa ruta → bones necesarios ────────────────────────────────────────────
// La primera clave que coincida (prefijo) gana.
const ROUTE_BONES: [string, string[]][] = [
  ['/dashboard', ['dashboard-main']],
  ['/anfitriona-dashboard', ['anfitriona-dashboard-main']],
  ['/anfitriona-asistencias', ['anfitriona-asistencias-main']],
  ['/cajero-anticipos', ['cajero-anticipos-main']],
  ['/cajero-asistencias', ['cajero-asistencias-main']],
  ['/cajero-propinas', ['cajero-propinas-main']],
  ['/garzon-anticipos', ['garzon-anticipos-main']],
  ['/garzon-asistencias', ['garzon-asistencias-main']],
  ['/garzon-propinas', ['garzon-propinas-main']],
  ['/error-logs', ['error-logs-main']],
  ['/profile', ['profile-main']],
  ['/categories', ['category-products-mobile', 'category-products-table']],
  ['/orders', ['orders-main']],
  ['/reports', ['reports-main']],
]

// ── Cache de nombres ya registrados ──────────────────────────────────────────
const registeredNames = new Set<string>()

/**
 * Registra los bones necesarios para la ruta dada.
 * Los bones ya registrados se saltan (idempotente).
 * Se puede llamar múltiples veces desde diferentes páginas sin problema.
 */
export async function registerBonesForRoute(pathname: string): Promise<void> {
  // Buscar la primera ruta que coincida como prefijo
  const match = ROUTE_BONES.find(([prefix]) => pathname.startsWith(prefix))
  if (!match) return

  const [, boneNames] = match
  const pending = boneNames.filter(name => !registeredNames.has(name))
  if (pending.length === 0) return

  const modules = await Promise.all(
    pending.map(name => {
      const loader = BONE_LOADERS[name]
      if (!loader) {
        console.warn(`[bones] No hay loader para "${name}"`)
        return null
      }
      return loader()
    })
  )

  const entries: Record<string, any> = {}
  for (let i = 0; i < pending.length; i++) {
    if (modules[i]) {
      entries[pending[i]] = modules[i]!.default
      registeredNames.add(pending[i])
    }
  }

  if (Object.keys(entries).length > 0) {
    registerBones(entries)
  }
}
