import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faUsers,
  faUser,
  faHome,
  faMoneyBill1Wave,
  faCreditCard,
  faCoins,
  faClock,
  faShoppingCart,
  faStop,
  faDollarSign,
  faEllipsisV,
  faEye,
  faEdit,
  faTrash,
  faCheckCircle,
  faTimesCircle,
  faPlus,
  faSearch,
  faLock,
  faGlassCheers,
  faTable,
  faGripHorizontal,
  faTimes,
} from '@fortawesome/free-solid-svg-icons';

// Add all icons to the library
library.add(
  faArrowLeft,
  faUsers,
  faUser,
  faHome,
  faMoneyBill1Wave,
  faCreditCard,
  faCoins,
  faClock,
  faShoppingCart,
  faStop,
  faDollarSign,
  faEllipsisV,
  faEye,
  faEdit,
  faTrash,
  faCheckCircle,
  faTimesCircle,
  faPlus,
  faSearch,
  faLock,
  faGlassCheers,
  faTable,
  faGripHorizontal,
  faTimes,
); 