-- Tabla para solicitudes de servicios desde pedidos
CREATE TABLE IF NOT EXISTS `solicitudes_servicios` (
  `id_solicitud` int NOT NULL AUTO_INCREMENT,
  `cliente_id` int DEFAULT NULL,
  `habitacion_id` int NOT NULL,
  `precio_servicio` decimal(10,2) NOT NULL DEFAULT 0,
  `precio_habitacion` decimal(10,2) NOT NULL DEFAULT 0,
  `anfitrionas_ids` JSON NOT NULL,
  `metodo_pago` varchar(50) NOT NULL,
  `tiempo` int NOT NULL,
  `total` decimal(10,2) NOT NULL,
  `iva` decimal(10,2) NOT NULL DEFAULT 0,
  `solicitado_por` int NOT NULL,
  `estado` enum('pendiente','aprobada','rechazada') NOT NULL DEFAULT 'pendiente',
  `motivo_rechazo` text,
  `procesado_por` int DEFAULT NULL,
  `fecha_solicitud` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_procesamiento` datetime DEFAULT NULL,
  PRIMARY KEY (`id_solicitud`),
  KEY `cliente_id` (`cliente_id`),
  KEY `habitacion_id` (`habitacion_id`),
  KEY `solicitado_por` (`solicitado_por`),
  KEY `procesado_por` (`procesado_por`),
  KEY `estado` (`estado`),
  CONSTRAINT `fk_solicitud_cliente` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id_cliente`),
  CONSTRAINT `fk_solicitud_habitacion` FOREIGN KEY (`habitacion_id`) REFERENCES `habitaciones` (`id_habitacion`),
  CONSTRAINT `fk_solicitud_solicitado` FOREIGN KEY (`solicitado_por`) REFERENCES `usuarios` (`id_usuario`),
  CONSTRAINT `fk_solicitud_procesado` FOREIGN KEY (`procesado_por`) REFERENCES `usuarios` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
