name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          # Agrega directamente la entrada del known_host de tu servidor
          echo "195.200.4.245 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAlUC400SiFTmB/j8+Q/lG10TNYLSR3FXAGW0+/s3E3D" >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/id_ed25519 root@195.200.4.245 "\
          cd /root/lasmunecasderamon && \
          git pull origin main && \
          docker-compose down && \
          docker-compose up -d --build \
          "
